[package]
name = "engine"
description = "The Rust bindings for the Citrus Engine, originally written in C++."
readme = "README.md"
license = "LGPL-2.1-only"
keywords = ["gamedev", "api", "game", "bindings"]
categories = ["api-bindings", "game-engines", "game-development"]
authors = ["Team Citrus"]
version = "0.0.1"
repository = "https://github.com/team-citrus/engine-rust/"
include = ["/src/rs"]

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

# TODO: Add more keys
